# Generated by Django 3.2.10 on 2023-02-13 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='admincontactdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NAME', models.CharField(blank=True, max_length=100, null=True)),
                ('EMAIL', models.EmailField(blank=True, max_length=254, null=True)),
                ('SUBJECT', models.CharField(blank=True, max_length=50, null=True)),
                ('MESSAGE', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='admindb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NAME', models.CharField(blank=True, max_length=100, null=True)),
                ('EMAIL', models.EmailField(blank=True, max_length=254, null=True)),
                ('NUMBER', models.IntegerField(blank=True, null=True)),
                ('USERNAME', models.CharField(blank=True, max_length=50, null=True)),
                ('PASSWORD', models.CharField(blank=True, max_length=50, null=True)),
                ('IMAGE', models.ImageField(blank=True, null=True, upload_to='profile')),
            ],
        ),
        migrations.CreateModel(
            name='categordb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NAME', models.CharField(blank=True, max_length=100, null=True)),
                ('DISCRIPTION', models.CharField(blank=True, max_length=100, null=True)),
                ('IMAGE', models.ImageField(blank=True, null=True, upload_to='profile')),
            ],
        ),
        migrations.CreateModel(
            name='productdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NAME', models.CharField(blank=True, max_length=100, null=True)),
                ('CATEGORY', models.CharField(blank=True, max_length=100, null=True)),
                ('PRIZE', models.IntegerField(blank=True, null=True)),
                ('QUANTITY', models.IntegerField(blank=True, null=True)),
                ('DISCRIPTION', models.CharField(blank=True, max_length=100, null=True)),
                ('IMAGE', models.ImageField(blank=True, null=True, upload_to='profile')),
            ],
        ),
    ]
